repos:
  - repo: local
    hooks:
      - id: ruff-fix-and-format
        name: Ruff Fix + Format
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-check
        name: Ruff Check (no fix)
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: true