name: Continuous Integration

env:
  DB_ENGINE: sqlite3
  DB_NAME: ':memory:'
  DJANGO_DEBUG: 'True'
  DJANGO_SECRET_KEY: 'insecure-default-key'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./src

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ---------- Python / Django ----------
      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Django tests
        run: uv run python manage.py test 
        
        # ---------- Front / Cypress ---------- 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cypress dependencies
        working-directory: ./infra/cypress
        run: npm install

      - name: Run Django server (background)
        working-directory: ./src
        run: |
          uv run manage.py migrate
          uv run manage.py runserver 0.0.0.0:8000 &
          sleep 5

      - name: Run Cypress tests
        working-directory: ./infra/cypress
        run: npm run cy:run